# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@3
# workflows:
#   use-my-orb:
#     jobs:
#       - cypress-io/run:
#           cypress-cache-key: custom-cypress-cache-v1-{{ arch }}-{{ checksum "package.json" }}
#           cypress-cache-path: ~/.cache/custom-dir/Cypress
#           cypress-command: npx cypress run
#           node-cache-version: v2


# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@3
# workflows:
#   use-my-orb:
#     jobs:
#       - cypress/run:
#           cypress-cache-key: custom-cypress-cache-v1-{{ arch }}-{{ checksum "package.json" }}
#           cypress-cache-path: ~/.cache/custom-dir/Cypress
#           cypress-command: npx cypress run --component
#           node-cache-version: v2


version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run: # "run" job comes from "Cypress" orb
          start-command: 'npm run start'